import { useState, React } from 'react'
import { motion } from 'framer-motion'

function Technology({ name, link }) {
  const [isOpen, setIsOpen] = useState(false)
  
  const renderUnopened = () => {
    return (
      <motion.div layout onClick={() => setIsOpen(!isOpen)} className='technologyCard'>
        <motion.img className='technology' src={link} alt={name} />
        <motion.p>{name}</motion.p>
      </motion.div>
    )
  }
  const renderOpened = () => {
    return (
      <motion.div layout onClick={() => setIsOpen(!isOpen)} className='openTechnologyCard'>
        <motion.img className='technology' src={link} alt={name} />
        <motion.p>{name}</motion.p>
        <p>Provided to YouTube by Shocking Music

Messages from the Stars (Sped Up) · The Rah Band · Richard Hewson · Richard Hewson

Messages from the Stars (Sped Up)

℗ Shocking Music

Released on: 2022-11-04

Auto-generated by YouTube.</p>
      </motion.div>
    )
  }
  return (
    <div className='immediateparent'>
      {isOpen?renderOpened():renderUnopened()}
    </div>
  )
    // <motion.div layout onClick={() => setIsOpen(!isOpen)} className='technologyCard'>
    //   <motion.img className='technology' src={link} alt={name} />
    //   <motion.p>{name}</motion.p>
    //   {isOpen && (
    //     <motion.div className='expanded-tech'>
    //       <p>I learned how to do this shit ez</p>
    //     </motion.div>
    //   )}
    // </motion.div >
}

export default Technology